services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: symfoshop_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfoshop
      MYSQL_USER: symfoshop
      MYSQL_PASSWORD: symfoshop123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - symfoshop_network

  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfoshop_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - php_cache:/var/www/html/var/cache
      - php_logs:/var/www/html/var/log
    depends_on:
      - mysql
    networks:
      - symfoshop_network
    env_file:
      - docker/docker.env
    environment:
      - DATABASE_URL=mysql://symfoshop:symfoshop123@mysql:3306/symfoshop?serverVersion=8.0
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: symfoshop_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/symfoshop.conf:/etc/nginx/conf.d/default.conf
      - nginx_cache:/var/cache/nginx
    depends_on:
      - php
    networks:
      - symfoshop_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M



volumes:
  mysql_data:
    driver: local
  php_cache:
    driver: local
  php_logs:
    driver: local
  nginx_cache:
    driver: local

networks:
  symfoshop_network:
    driver: bridge 