framework:
    http_method_override: false
    handle_all_throwables: true
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions'
        cookie_secure: true
        cookie_samesite: lax
    php_errors:
        log: true 